help:
    @just --list

run-counter:
    cd counter && mvn clean
    cd counter && mvn package -DskipTests
    cd counter && mvn dependency:copy-dependencies
    clear
    @cd counter && java -p target/dependency:target/classes --enable-native-access=dev.weisz.boba -m dev.weisz.boba.counter/counter.dev.weisz.boba.Main

run-tct:
    cd tictactoe && mvn clean
    cd tictactoe && mvn package -DskipTests
    mvn dependency:copy-dependencies
    clear
    @cd tictactoe && java -p target/dependency:target/classes --enable-native-access=dev.weisz.boba -m dev.weisz.boba.tictactoe/tictactoe.dev.weisz.boba.Main
